#---
#apiVersion: v1
#kind: Namespace
#metadata:
#    name: influxdb
#---
apiVersion: apps/v1
#kind: StatefulSet
kind: Deployment
metadata:
    labels:
        app: influxdb
    name: influxdb
    namespace: influx_DB
spec:
    replicas: 1
    selector:
        matchLabels:
            app: influxdb
#    serviceName: influxdb
    template:
        metadata:
            labels:
                app: influxdb
        spec:
            containers:
              - image: quay.io/influxdb/influxdb:v2.0.1
                name: influxdb
                ports:
                  - containerPort: 8086
                    name: influxdb
                volumeMounts:
                  - mountPath: /root/.influxdbv2
                    name: influx_DB-pv

            volumes:
               - name: influx_DB-pv
                 persistentVolumeClaim:
                    claimName: influx_DB-pvc


                    #    volumeClaimTemplates:
                    #      - metadata:
                    #            name: influx_DB-pvc
                    #            namespace: influxdb
                    #        spec:
                    #            accessModes:
                    #              - ReadWriteOnce
                    #            resources:
                    #                requests:
                    #                    storage: 10G
---
apiVersion: v1
kind: Service
metadata:
    name: influxdb
    namespace: influx_DB
spec:
    ports:
      - name: influxdb
        port: 8086
        targetPort: 8086
    selector:
        app: influxdb
    type: ClusterIP
