apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx_DB-pvc
  namespace: influx_DB
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: metrics-nfs-storage

