apiVersion: v1
kind: Secret
metadata:
  name: mypostgres-secret
  namespace: kubegres-system2
type: Opaque
stringData:
  superUserPassword: postgresSuperUserPsw
  replicationUserPassword: postgresReplicaPsw
  myAppUserPassword: Y6MTmRl9nEfaOJrq9CYVSKJM 
