apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name:  prometheus-pvc
  namespace: promet
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 2Gi
  storageClassName: metrics-nfs-storage

