apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - image: telegraf:latest
          name: telegraf
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
              #          envFrom:
              #            - secretRef:
              #                name: telegraf-secrets
          volumeMounts:
             - name: telegraf-pv
               mountPath: /etc/telegraf/telegraf.com
              #              subPath: telegraf.conf
              #              readOnly: true
      volumes:
         - name: telegraf-pv
           persistentVolumeClaim:
              claimName: telegraf-pvc
              #          #configMap:
              #          #  name: telegraf-config
              #
