apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: telegraf-pvc
  namespace: telegraf
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 2Gi
  storageClassName: metrics-nfs-storage

