apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: promet
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 15s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
            #      alertmanagers:
            #      - scheme: http
            #        static_configs:
            #        - targets:
            #          - "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: 'heplify-server'
        static_configs:
          - targets: ['heplify-metrics.heplify.svc.cluster.local:9096']
