apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: metrics-nfs-storage
  volumeName: grafana-pv
  type: nfs
  claimRef:
    name: grafana-pvc
    namespace: grafana
