#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: grafana-pv
#spec:
#  capacity:
#    storage: 1Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Recycle
#  storageClassName: metrics-nfs-storage
#  type: nfs
#  claimRef:
#    name: grafana-pvc
#    namespace: grafana
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: grafana
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.25.199
    path: "/mnt/tnas-de/icc-recordings"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: grafana
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeName: grafana-pv
  resources:
    requests:
      storage: 80Gi
