#apiVersion: v1
#kind: Service
#metadata:
#  annotations:
#    kompose.cmd: kompose convert -f docker-compose.yml
#    kompose.version: 1.26.1 (a9d05d509)
#    org.label-schema.group: monitoring
#  creationTimestamp: null
#  labels:
#    io.kompose.service: heplify-server
#  name: heplify-server
#  namespace: heplify
#
#spec:
#  ports:
#    - name: "9060"
#      port: 9060
#      targetPort: 9060
#    - name: 9060-udp
#      port: 9060
#      protocol: UDP
#      targetPort: 9060
#    - name: "tcp-9061"
#      port: 9061
#      targetPort: 9061
#    - name: "9090"
#      port: 9090
#      targetPort: 9090
#    - name: "9096"
#      port: 9096
#      targetPort: 9096
#  selector:
#    io.kompose.service: heplify-server
#status:
#  loadBalancer: {}
#---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: heplify-web
  name: heplify-web
  namespace: heplify

spec:
  type: NodePort
  ports:
    - name: "9060-udp"
      port: 9060
      protocol: UDP
      targetPort: 9060
      nodePort: 30960
    - name: "9061"
      port: 9061
      targetPort: 9061
      nodePort: 30961
    - name: "9090"
      port: 9090
      targetPort: 9090
    - name: "9096"
      port: 9096
      targetPort: 9096

  selector:
    io.kompose.service: heplify-server

