apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: homer-webapp
  name: homer-webapp
  namespace: homer
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: homer-webapp
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: homer-webapp
    spec:
      containers:
        - name: homer-webapp
          image: sipcapture/webapp
          env:
            - name: PROM_HOST
              value: prometheus
          envFrom:
            - secretRef:
                name: postgresql-homer-secret
          ports:
            - containerPort: 80
      restartPolicy: Always
status: {}
