apiVersion: v1

kind: Secret
metadata:
  name: telegraf-secrets
  namespace: telegraf2
type: Opaque
stringData:
  INFLUXDB_DB: telegraf
  INFLUXDB_URL: http://10.233.48.203:8086
  INFLUXDB_USER: admin
  INFLUXDB_USER_PASSWORD: kraken

