apiVersion: v1
kind: Secret
metadata:
  name: mypostgres-secret
  namespace: kubegres_DB-system
type: Opaque
stringData:
  superUserPassword: postgresSuperUserPsw
  replicationUserPassword: postgresReplicaPsw
  myAppUserPassword: myAppUserPsw
