apiVersion: v1
kind: Service
metadata:
  name: kubegres_DB-nodeport
  namespace: kubegres_DB-system

spec:
  type: NodePort
  clusterIP: 10.233.42.168
  selector:
    app: mypostgres
    replicationRole: primary
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5432
      targetPort: 5432
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
